# Generated by Django 5.1.1 on 2024-10-17 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 13, 34, 46, 716288), editable=False, verbose_name='last login'),
        ),
    ]
