# Generated by Django 5.1.1 on 2024-10-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='შეკვეთის თარიღი')),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Delivered')], default='Pending', max_length=100, verbose_name='სტატუსი')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='რაოდენობა')),
                ('order_address', models.CharField(max_length=100, verbose_name='მისამართი')),
            ],
        ),
    ]
