# Generated by Django 5.1.1 on 2024-10-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='შეკვეთის თარიღი')),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Delivered')], default='Pending', max_length=100, verbose_name='სტატუსი')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='რაოდენობა')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ჯამური ფასი')),
                ('order_address', models.CharField(max_length=100, verbose_name='მისამართი')),
                ('order_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='კატეგორია')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='პროდუქტი')),
            ],
        ),
    ]
