# Generated by Django 5.1.1 on 2024-10-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_product_id_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
